[build]
  command = "corepack enable && pnpm install --frozen-lockfile && pnpm --filter client build"
  publish = "client/dist"

[build.environment]
  VITE_WS_ENDPOINT = "wss://api.mutante.club"
  VITE_HTTP_ENDPOINT = "https://api.mutante.club"

# Rule for router history mode
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
