[build]
  command = "cd types && npm i && cd ../client && npm i && npm run build"
  publish = "client/dist"

[build.environment]
  VITE_WS_ENDPOINT = "wss://api.mutante.club"
  VITE_HTTP_ENDPOINT = "https://api.mutante.club"

# Rule for router history mode
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
