# fly.toml app configuration file generated for club-mutant-pot-provider on 2026-01-30T15:45:47-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'club-mutant-pot-provider'
primary_region = 'iad'

[build]
  image = 'brainicism/bgutil-ytdlp-pot-provider:latest'

[http_service]
  internal_port = 4416
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
